-- Define your icons here. These are used by blink.cmp and breadcrumbs/navic.
-- To find icons, use https://www.nerdfonts.com/cheat-sheet or :Snacks.picker.icons()
local M = {
    Array = "",
    Boolean = "",
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Copilot = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "",
    Module = "",
    Namespace = "",
    Null = "󰟢",
    Number = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "󰦨",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
}

return M
